name: SFTP transfer and SSH restart

on:
  push:
    branches:
      - main

jobs:
  transfer_and_restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client and lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client lftp

    - name: Transfer files to server
      run: |
        lftp -c "open -u ${{ secrets.USERNAME }},${{ secrets.PASSWORD }} -e 'set sftp:auto-confirm yes; mirror -R ./ /root/Documents/PlanksCutter; exit' sftp://veagle.fr"

    - name: Restart Planks Cutter service
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -oStrictHostKeyChecking=no -l ${{ secrets.USERNAME }} veagle.fr "systemctl restart planks-cutter"
