name: SFTP transfer and SSH restart

on:
  push:
    branches:
      - main

jobs:
  transfer_and_restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH and SFTP clients
      run: sudo apt-get install -y openssh-client

    - name: Transfer files to server
      run: |
        echo "put -r ./ /root/Documents/PlanksCutter" > sftp_commands
        sftp -oStrictHostKeyChecking=no -b sftp_commands ${SFTP_USERNAME}@veagle.fr
      env:
        SFTP_USERNAME: ${{ secrets.USERNAME }}
        SFTP_PASSWORD: ${{ secrets.PASSWORD }}

    - name: Restart Planks Cutter service
      run: ssh -oStrictHostKeyChecking=no -l ${SSH_USERNAME} -p 22 veagle.fr "systemctl restart planks-cutter"
      env:
        SSH_USERNAME: ${{ secrets.USERNAME }}
        SSH_PASSWORD: ${{ secrets.PASSWORD }}
